version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Juanan_password
      MYSQL_DATABASE: tienda
      MYSQL_USER: Juanan
      MYSQL_PASSWORD: Juanan_password
    networks:
      - net_tienda

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: Juanan
      WORDPRESS_DB_PASSWORD: Juanan_password
      WORDPRESS_DB_NAME: tienda
    ports:
      - "8080:80"
    networks:
      - net_tienda

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Juanan_password
    ports:
      - "8000:80"
    networks:
      - net_tienda

volumes:
  db_data:
  wp_data:

networks:
  net_tienda:
